defaultContentLanguage = "en"
languageCode = "en-us"
metaDataFormat = "yaml"
title = "Keptn"
uglyURLs = false
enableRobotsTXT = true
pluralizeListTitles = false
canonifyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]
anchor = "smart"
enableGitInfo = true
enableEmoji = true
buildFuture = true
ignoreFiles = [ "OWNERS" ]
staticDir = ["static", "generated"]

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats]
    [outputFormats.RSS]
        baseName = "feed"

[params]
    google_analytics_id="UA-133584243-1"
