defaultContentLanguage = "en"
languageCode = "en-us"
metaDataFormat = "yaml"
title = "Keptn"
uglyURLs = false
enableRobotsTXT = true
pluralizeListTitles = false
canonifyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]
anchor = "smart"
enableGitInfo = true
enableEmoji = true
buildFuture = true
ignoreFiles = [ "OWNERS" ]
staticDir = ["static", "generated"]

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
	plainIDAnchors = true
    # See https://github.com/gohugoio/hugo/issues/2424
	hrefTargetBlank = false
    angledQuotes = false
    latexDashes = true
    extensions = [""]

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats]
    [outputFormats.RSS]
        baseName = "feed"

[params]
    google_analytics_id="UA-133584243-1"
